export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP'
export const ACTIVATION = 'ACTIVATION';
export const FORGETPASSWORD = 'FORGETPASSWORD'
export const RESETPASSWORD = 'RESETPASSWORD'

export const GET_ALL_PROGRAMS = 'GET_ALL_PROGRAMS'
export const GET_PROGRAM = 'GET_PROGRAM'
export const GET_PROGRAMS_BY_SEARCH = 'GET_PROGRAMS_BY_SEARCH'


export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'
